//! Pins the zcashd RPC method status table in the Zallet book to the set of
//! JSON-RPC methods that are actually registered.
//!
//! Unlike `book/src/rpc/methods.md`, the status table at
//! `book/src/zcashd/rpc_status.md` is maintained by hand, so nothing updates it
//! when a method lands. This test fails whenever the table and the method
//! registry disagree:
//!
//! - a method the table marks "Not yet implemented", "Not planned", or
//!   "Omitted" is registered (the row is stale; update its status), or
//! - a method the table marks "Implemented" is not registered.

#![cfg(zallet_build = "wallet")]

use std::collections::HashSet;

/// The method reference generated by `generate_rpc_book_reference` in
/// `build.rs`, which contains one `` ## `name` `` heading per registered
/// JSON-RPC method.
const GENERATED: &str = include_str!(concat!(env!("OUT_DIR"), "/rpc_methods.md"));

/// The hand-maintained status table in the book.
const STATUS_TABLE_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../book/src/zcashd/rpc_status.md",
);

#[test]
fn book_rpc_status_table_matches_registry() {
    let registered = GENERATED
        .lines()
        .filter_map(|line| line.strip_prefix("## `")?.strip_suffix('`'))
        .collect::<HashSet<_>>();
    assert!(
        !registered.is_empty(),
        "failed to parse any method headings out of the generated reference",
    );

    let table = std::fs::read_to_string(STATUS_TABLE_PATH).expect("status table exists");

    let mut errors = vec![];
    for line in table.lines() {
        // Method rows have the form `| `method` | Status | Notes |`; every
        // other line (including the header and separator rows) fails one of
        // these matches and is skipped.
        let Some(row) = line.strip_prefix("| `") else {
            continue;
        };
        let Some((method, rest)) = row.split_once("` | ") else {
            continue;
        };
        let Some((status, _notes)) = rest.split_once(" | ") else {
            continue;
        };

        let is_registered = registered.contains(method);
        if status.starts_with("Implemented") && !is_registered {
            errors.push(format!(
                "`{method}` is marked \"{status}\" but is not a registered method"
            ));
        }
        if ["Not yet implemented", "Not planned", "Omitted"]
            .iter()
            .any(|absent| status.starts_with(absent))
            && is_registered
        {
            errors.push(format!(
                "`{method}` is a registered method but the table still says \"{status}\""
            ));
        }
    }

    assert!(
        errors.is_empty(),
        "book/src/zcashd/rpc_status.md disagrees with the RPC method registry:\n  {}",
        errors.join("\n  "),
    );
}
